version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::960351580303:user/aws-sam-cli-managed-dev-vg-pipeline-r-PipelineUser-ZXO0LSX1OTQ1"
permissions_provider = "AWS IAM"

[dev-vg]
[dev-vg.pipeline_bootstrap]
[dev-vg.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::960351580303:role/aws-sam-cli-managed-dev-vg-p-PipelineExecutionRole-1TEXFHG14LLLB"
cloudformation_execution_role = "arn:aws:iam::960351580303:role/aws-sam-cli-managed-dev-v-CloudFormationExecutionR-KHI2OGJPMI0Y"
artifacts_bucket = "aws-sam-cli-managed-dev-vg-pipeli-artifactsbucket-1be881734ond5"
image_repository = ""
region = "ap-south-1"

[prod-vg]
[prod-vg.pipeline_bootstrap]
[prod-vg.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::960351580303:role/aws-sam-cli-managed-prod-vg-PipelineExecutionRole-KQ77D8IG9L34"
cloudformation_execution_role = "arn:aws:iam::960351580303:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-2IXWZH05MOIE"
artifacts_bucket = "aws-sam-cli-managed-prod-vg-pipel-artifactsbucket-5oq0mmvmled1"
image_repository = ""
region = "ap-south-1"
